<?php
/**
 * Auto-Install Script
 * Run this file on first-time setup
 */

// Enable error reporting for installer (helps debug installation issues)
if (!defined('APP_ENV')) {
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
    ini_set('display_startup_errors', 1);
}

// Start session for installer
if (session_status() === PHP_SESSION_NONE) {
    @session_start();
}

// Check if already installed
$configFile = __DIR__ . '/config/config.php';
if (file_exists($configFile)) {
    try {
        $config = @file_get_contents($configFile);
        if ($config !== false) {
            // Check if database is configured (not default localhost/empty)
            $isDefault = (strpos($config, "define('DB_HOST', 'localhost')") !== false && 
                         strpos($config, "define('DB_NAME', 'timeline_db')") !== false &&
                         strpos($config, "define('DB_USER', 'root')") !== false);
            
            if (!$isDefault) {
                die('Application is already installed. Delete config/config.php to reinstall.');
            }
        }
    } catch (Exception $e) {
        // If we can't read config, allow installation to proceed
    }
}

$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;
$error = '';
$success = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if ($step == 1) {
        // Database configuration
        $dbHost = isset($_POST['db_host']) ? trim($_POST['db_host']) : 'localhost';
        $dbName = isset($_POST['db_name']) ? trim($_POST['db_name']) : 'timeline_db';
        $dbUser = isset($_POST['db_user']) ? trim($_POST['db_user']) : 'root';
        $dbPass = isset($_POST['db_pass']) ? $_POST['db_pass'] : '';
        
        // Test database connection
        try {
            $pdo = new PDO("mysql:host={$dbHost};charset=utf8mb4", $dbUser, $dbPass);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            
            // Create database if it doesn't exist
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            
            // Store in session for next step
            $_SESSION['install'] = [
                'db_host' => $dbHost,
                'db_name' => $dbName,
                'db_user' => $dbUser,
                'db_pass' => $dbPass
            ];
            
            header('Location: ?step=2');
            exit;
        } catch (PDOException $e) {
            $error = 'Database connection failed: ' . $e->getMessage();
        }
    } elseif ($step == 2) {
        // Admin account creation
        if (!isset($_SESSION['install'])) {
            header('Location: ?step=1');
            exit;
        }
        
        $adminEmail = isset($_POST['admin_email']) ? trim($_POST['admin_email']) : '';
        $adminPassword = isset($_POST['admin_password']) ? $_POST['admin_password'] : '';
        $adminPasswordConfirm = isset($_POST['admin_password_confirm']) ? $_POST['admin_password_confirm'] : '';
        
        if (empty($adminEmail) || empty($adminPassword)) {
            $error = 'Email and password are required';
        } elseif (!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) {
            $error = 'Please enter a valid email address';
        } elseif ($adminPassword !== $adminPasswordConfirm) {
            $error = 'Passwords do not match';
        } elseif (strlen($adminPassword) < 8) {
            $error = 'Password must be at least 8 characters';
        } else {
            // Create config file
            $dbHost = addslashes($_SESSION['install']['db_host']);
            $dbName = addslashes($_SESSION['install']['db_name']);
            $dbUser = addslashes($_SESSION['install']['db_user']);
            $dbPass = addslashes($_SESSION['install']['db_pass']);
            
            $config = <<<PHP
<?php
/**
 * Application Configuration
 * Auto-generated by installer
 */

// Database Configuration
define('DB_HOST', '{$dbHost}');
define('DB_NAME', '{$dbName}');
define('DB_USER', '{$dbUser}');
define('DB_PASS', '{$dbPass}');
define('DB_CHARSET', 'utf8mb4');

// Application Configuration
define('APP_NAME', 'Timeline.co.zw');
\$protocol = (!empty(\$_SERVER['HTTPS']) && \$_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
define('APP_URL', \$protocol . '://' . \$_SERVER['HTTP_HOST']);
define('APP_ENV', 'production');

// Security
define('SESSION_LIFETIME', 3600);
define('PASSWORD_MIN_LENGTH', 8);
define('CSRF_TOKEN_NAME', 'csrf_token');

// API Keys (Set via admin panel)
define('YOUTUBE_API_KEY', '');
define('ADSENSE_CLIENT_ID', '');
define('NEWS_API_KEY', '');
define('LASTFM_API_KEY', '');
define('SPOTIFY_CLIENT_ID', '');
define('SPOTIFY_CLIENT_SECRET', '');

// Cache Configuration
define('CACHE_DURATION', 259200); // 3 days
define('CACHE_DIR', __DIR__ . '/../cache/');

// Paths
define('BASE_PATH', dirname(__DIR__));
define('CLASSES_PATH', BASE_PATH . '/classes');
define('MIGRATIONS_PATH', BASE_PATH . '/database/migrations');
define('UPLOADS_PATH', BASE_PATH . '/uploads');

// Error Reporting
if (APP_ENV === 'development') {
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
} else {
    error_reporting(0);
    ini_set('display_errors', 0);
}

date_default_timezone_set('UTC');
PHP;
            
            // Check if config directory is writable
            $configDir = __DIR__ . '/config';
            if (!is_dir($configDir)) {
                if (!mkdir($configDir, 0755, true)) {
                    $error = 'Cannot create config directory. Please create it manually with write permissions.';
                }
            }
            
            if (!is_writable($configDir)) {
                $error = 'Config directory is not writable. Please set permissions to 755 or 775.';
            } else {
                // Write config file
                if (file_put_contents(__DIR__ . '/config/config.php', $config) === false) {
                    $error = 'Cannot write config file. Please check directory permissions.';
                } else {
                    // Run migrations and create admin user
                    try {
                        // Load config first (we just created it)
                        require_once __DIR__ . '/config/config.php';
                        
                        // Autoloader for classes
                        spl_autoload_register(function ($class) {
                            $file = CLASSES_PATH . '/' . $class . '.php';
                            if (file_exists($file)) {
                                require_once $file;
                            }
                        });
                        
                        // Start session if needed
                        if (session_status() === PHP_SESSION_NONE) {
                            @session_start();
                        }
                        
                        $migration = new Migration();
                        $migration->runMigrations();
                        
                        $auth = new Auth();
                        $auth->createUser($adminEmail, $adminPassword, 'admin');
                        
                        // Create required directories
                        $directories = [
                            __DIR__ . '/cache',
                            __DIR__ . '/uploads',
                            __DIR__ . '/logs'
                        ];
                        
                        foreach ($directories as $dir) {
                            if (!is_dir($dir)) {
                                if (!mkdir($dir, 0755, true)) {
                                    error_log("Warning: Could not create directory: {$dir}");
                                }
                            }
                        }
                        
                        // Create .htaccess in cache and uploads for security
                        $htaccessContent = "Order Deny,Allow\nDeny from all\n";
                        file_put_contents(__DIR__ . '/cache/.htaccess', $htaccessContent);
                        file_put_contents(__DIR__ . '/uploads/.htaccess', $htaccessContent);
                        
                        session_destroy();
                        
                        header('Location: ?step=3');
                        exit;
                    } catch (Exception $e) {
                        $errorMsg = $e->getMessage();
                        $errorTrace = $e->getTraceAsString();
                        
                        // Log full error for debugging
                        error_log("Installation Error: " . $errorMsg);
                        error_log("Stack Trace: " . $errorTrace);
                        
                        $error = 'Installation failed: ' . htmlspecialchars($errorMsg) . 
                                '. Please check error logs for details.';
                        
                        // Delete config file if installation failed
                        if (file_exists(__DIR__ . '/config/config.php')) {
                            @unlink(__DIR__ . '/config/config.php');
                        }
                    } catch (Throwable $e) {
                        // Catch any other errors (ParseError, etc.)
                        $errorMsg = $e->getMessage();
                        error_log("Fatal Installation Error: " . $errorMsg);
                        $error = 'Fatal error during installation: ' . htmlspecialchars($errorMsg) . 
                                '. Please check PHP error logs.';
                        
                        if (file_exists(__DIR__ . '/config/config.php')) {
                            @unlink(__DIR__ . '/config/config.php');
                        }
                    }
                }
            }
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Installation - Timeline.co.zw</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 2rem;
        }
        .install-container {
            background: white;
            border-radius: 10px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
            max-width: 600px;
            width: 100%;
            padding: 3rem;
        }
        h1 { margin-bottom: 0.5rem; color: #333; }
        .subtitle { color: #666; margin-bottom: 2rem; }
        .form-group { margin-bottom: 1.5rem; }
        label { display: block; margin-bottom: 0.5rem; color: #333; font-weight: 500; }
        input { width: 100%; padding: 0.75rem; border: 2px solid #e0e0e0; border-radius: 5px; font-size: 1rem; }
        input:focus { outline: none; border-color: #667eea; }
        .btn { width: 100%; padding: 0.875rem; background: #667eea; color: white; border: none; border-radius: 5px; font-size: 1rem; font-weight: 600; cursor: pointer; margin-top: 1rem; }
        .btn:hover { background: #5568d3; }
        .error { background: #fee; color: #c33; padding: 1rem; border-radius: 5px; margin-bottom: 1.5rem; }
        .success { background: #efe; color: #0a5; padding: 1rem; border-radius: 5px; margin-bottom: 1.5rem; }
        .step-indicator { display: flex; justify-content: space-between; margin-bottom: 2rem; }
        .step { flex: 1; text-align: center; padding: 0.5rem; border-bottom: 3px solid #e0e0e0; }
        .step.active { border-color: #667eea; color: #667eea; font-weight: 600; }
    </style>
</head>
<body>
    <div class="install-container">
        <h1>🚀 Installation Wizard</h1>
        <p class="subtitle">Welcome! Let's set up your Timeline.co.zw application</p>
        
        <div class="step-indicator">
            <div class="step <?php echo $step >= 1 ? 'active' : ''; ?>">1. Database</div>
            <div class="step <?php echo $step >= 2 ? 'active' : ''; ?>">2. Admin Account</div>
            <div class="step <?php echo $step >= 3 ? 'active' : ''; ?>">3. Complete</div>
        </div>
        
        <?php if ($error): ?>
            <div class="error"><?php echo htmlspecialchars($error); ?></div>
        <?php endif; ?>
        
        <?php if ($step == 1): ?>
            <form method="POST">
                <div class="form-group">
                    <label>Database Host</label>
                    <input type="text" name="db_host" value="localhost" required>
                </div>
                <div class="form-group">
                    <label>Database Name</label>
                    <input type="text" name="db_name" value="timeline_db" required>
                </div>
                <div class="form-group">
                    <label>Database User</label>
                    <input type="text" name="db_user" value="root" required>
                </div>
                <div class="form-group">
                    <label>Database Password</label>
                    <input type="password" name="db_pass" value="">
                </div>
                <button type="submit" class="btn">Continue</button>
            </form>
        <?php elseif ($step == 2): ?>
            <form method="POST">
                <div class="form-group">
                    <label>Admin Email</label>
                    <input type="email" name="admin_email" required>
                </div>
                <div class="form-group">
                    <label>Admin Password</label>
                    <input type="password" name="admin_password" required minlength="8">
                </div>
                <div class="form-group">
                    <label>Confirm Password</label>
                    <input type="password" name="admin_password_confirm" required minlength="8">
                </div>
                <button type="submit" class="btn">Complete Installation</button>
            </form>
        <?php elseif ($step == 3): ?>
            <div class="success">
                <h2>✅ Installation Complete!</h2>
                <p>Your application has been successfully installed.</p>
                <p style="margin-top: 1rem;">
                    <a href="/admin/login.php" style="color: #667eea; font-weight: 600;">Go to Admin Panel →</a>
                </p>
            </div>
        <?php endif; ?>
    </div>
</body>
</html>

