<?php
/**
 * Application Configuration
 * This file is auto-generated by the installer
 */

// Database Configuration
define('DB_HOST', 'localhost');
define('DB_NAME', 'timeline_db');
define('DB_USER', 'root');
define('DB_PASS', '');
define('DB_CHARSET', 'utf8mb4');

// Application Configuration
define('APP_NAME', 'Timeline.co.zw');
define('APP_URL', 'http://localhost');
define('APP_ENV', 'production'); // development, production

// Security
define('SESSION_LIFETIME', 3600); // 1 hour
define('PASSWORD_MIN_LENGTH', 8);
define('CSRF_TOKEN_NAME', 'csrf_token');

// API Keys (Set via admin panel)
define('YOUTUBE_API_KEY', '');
define('ADSENSE_CLIENT_ID', '');
define('NEWS_API_KEY', '');
define('LASTFM_API_KEY', '');
define('SPOTIFY_CLIENT_ID', '');
define('SPOTIFY_CLIENT_SECRET', '');

// Cache Configuration
define('CACHE_DURATION', 259200); // 3 days in seconds (default, can be overridden by admin settings)
define('CACHE_DIR', __DIR__ . '/../cache/');

// Paths
define('BASE_PATH', dirname(__DIR__));
define('CLASSES_PATH', BASE_PATH . '/classes');
define('MIGRATIONS_PATH', BASE_PATH . '/database/migrations');
define('UPLOADS_PATH', BASE_PATH . '/uploads');

// Error Reporting
if (APP_ENV === 'development') {
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
} else {
    error_reporting(0);
    ini_set('display_errors', 0);
}

// Timezone
date_default_timezone_set('UTC');

